#ifndef QTHANDLEBARS_GLOBAL_H
#define QTHANDLEBARS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTHANDLEBARS_LIBRARY)
#  define QTHANDLEBARSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTHANDLEBARSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTHANDLEBARS_GLOBAL_H
